"""
Methods regarding pentagonal numbers

Pentagonal numbers are generated by the formula, P_n = n(3n-1)/2. The first ten
pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
"""

from misc import solve_quadratic

def is_pentagonal(n):
    """
    Determines if n is a pentagonal number
    :param n: int
    :return True if n is pentagonal, False otherwise
    """
    assert isinstance(n, int), "n must be integer, you sent in {}".format(n)
    assert n >=1, "n must be >= 1, you sent in {}".format(n)
    r1, r2 = solve_quadratic(1.5, -0.5, -n)
    # r1 will be my larger root
    if r1 > 0 and r1 == int(r1):
        return True
    return False

